env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  object-curly-spacing:
    - error
    - always
  require-jsdoc: off
  quotes:
    - error
    - single
